# Generated by Django 5.1.5 on 2025-01-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('power_rating_watts', models.FloatField(help_text='Power rating in watts')),
                ('daily_usage_hours', models.FloatField(help_text='Daily usage in hours')),
                ('days_used', models.FloatField(help_text='Days used in a month')),
            ],
        ),
    ]
