# Generated by Django 5.1.5 on 2025-01-30 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliance',
            old_name='name',
            new_name='appliances',
        ),
        migrations.RenameField(
            model_name='appliance',
            old_name='days_used',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='appliance',
            old_name='daily_usage_hours',
            new_name='hours',
        ),
        migrations.RenameField(
            model_name='appliance',
            old_name='power_rating_watts',
            new_name='power',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('energy_usage', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
